server:
  port: 8081

spring:
  application:
    name: livre-service
  datasource:
    url: jdbc:h2:mem:livredb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console